package com.sanjkv.todo;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;

import androidx.activity.result.ActivityResult;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.ActivityCallback;
import com.getcapacitor.annotation.CapacitorPlugin;

import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;

/**
 * Bridges the web layer to {@link TaskStore}, and to the system document picker
 * for backups.
 *
 * <p>App-local, so it is registered by hand in MainActivity — assets/capacitor
 * .plugins.json is regenerated by `cap sync` from npm packages and would drop
 * an entry added there.
 */
@CapacitorPlugin(name = "TodoStore")
public class TodoStorePlugin extends Plugin {

    /** Enough for any plausible task list; a guard against picking a video. */
    private static final int MAX_IMPORT_BYTES = 16 * 1024 * 1024;

    @PluginMethod
    public void read(PluginCall call) {
        try {
            String text = TaskStore.read(getContext());
            JSObject result = new JSObject();
            // Only set when there is something to report. JSObject extends
            // org.json.JSONObject, whose put(name, null) *removes* the key, so
            // "no document yet" reaches JS as {} either way — store.js reads
            // any non-string as null rather than trusting the key to be there.
            if (text != null) {
                result.put("value", text);
            }
            call.resolve(result);
        } catch (IOException e) {
            call.reject("Could not read the task document", e);
        }
    }

    @PluginMethod
    public void write(PluginCall call) {
        String value = call.getString("value");
        if (value == null) {
            call.reject("value is required");
            return;
        }
        try {
            TaskStore.write(getContext(), value);
            call.resolve();
        } catch (IOException e) {
            // Never resolve a failed write: the web layer keeps the in-memory
            // list and surfaces an error rather than believing it is saved.
            call.reject("Could not write the task document", e);
        }
    }

    @PluginMethod
    public void exportDoc(PluginCall call) {
        if (call.getString("value") == null) {
            call.reject("value is required");
            return;
        }
        Intent intent = new Intent(Intent.ACTION_CREATE_DOCUMENT)
            .addCategory(Intent.CATEGORY_OPENABLE)
            .setType("application/json")
            .putExtra(Intent.EXTRA_TITLE, call.getString("name", "todo-backup.json"));

        // The text rides along on the saved call, so the callback can read it
        // back without the plugin holding state across the picker.
        startActivityForResult(call, intent, "exportResult");
    }

    @ActivityCallback
    private void exportResult(final PluginCall call, ActivityResult result) {
        if (call == null) {
            return;
        }
        final Uri uri = uriFrom(result);
        if (uri == null) {
            // Backing out of the picker is a choice, not a failure.
            call.resolve(saved(false));
            return;
        }

        // Activity results arrive on the main thread, unlike @PluginMethod
        // bodies. The URI may belong to a cloud provider, so keep the I/O off it.
        execute(new Runnable() {
            @Override
            public void run() {
                try {
                    writeToUri(uri, call.getString("value", ""));
                    call.resolve(saved(true));
                } catch (IOException e) {
                    call.reject("Could not write the backup", e);
                }
            }
        });
    }

    @PluginMethod
    public void importDoc(PluginCall call) {
        // A .json file comes back as application/octet-stream or text/plain from
        // the Downloads provider and most file managers, so a strict
        // application/json filter greys out the user's own backup. Offer
        // everything and list the types that should look selectable.
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT)
            .addCategory(Intent.CATEGORY_OPENABLE)
            .setType("*/*")
            .putExtra(
                Intent.EXTRA_MIME_TYPES,
                new String[] { "application/json", "text/json", "text/plain", "application/octet-stream" }
            );

        startActivityForResult(call, intent, "importResult");
    }

    @ActivityCallback
    private void importResult(final PluginCall call, ActivityResult result) {
        if (call == null) {
            return;
        }
        final Uri uri = uriFrom(result);
        if (uri == null) {
            JSObject cancelled = new JSObject();
            cancelled.put("cancelled", true);
            call.resolve(cancelled);
            return;
        }

        execute(new Runnable() {
            @Override
            public void run() {
                try {
                    JSObject payload = new JSObject();
                    payload.put("value", readFromUri(uri));
                    call.resolve(payload);
                } catch (IOException e) {
                    call.reject("Could not read that file", e);
                }
            }
        });
    }

    private static JSObject saved(boolean value) {
        JSObject result = new JSObject();
        result.put("saved", value);
        return result;
    }

    private static Uri uriFrom(ActivityResult result) {
        if (result == null || result.getResultCode() != Activity.RESULT_OK) {
            return null;
        }
        Intent data = result.getData();
        return data == null ? null : data.getData();
    }

    /**
     * Opening with "wt" rather than the default "w": several providers do not
     * truncate on "w", so overwriting a longer backup leaves the tail of the old
     * one behind and the result is not valid JSON. Some providers reject "wt"
     * outright, hence the fallback.
     */
    private void writeToUri(Uri uri, String text) throws IOException {
        byte[] bytes = text.getBytes(StandardCharsets.UTF_8);
        OutputStream out = null;
        try {
            try {
                out = getContext().getContentResolver().openOutputStream(uri, "wt");
            } catch (IllegalArgumentException | IOException truncateUnsupported) {
                out = null;
            }

            if (out == null) {
                out = getContext().getContentResolver().openOutputStream(uri, "w");
                if (out instanceof FileOutputStream) {
                    ((FileOutputStream) out).getChannel().truncate(0);
                }
            }

            if (out == null) {
                throw new IOException("The picker returned a location that cannot be written");
            }

            out.write(bytes);
            out.flush();
        } finally {
            if (out != null) {
                try {
                    out.close();
                } catch (IOException ignored) {}
            }
        }
    }

    private String readFromUri(Uri uri) throws IOException {
        InputStream in = getContext().getContentResolver().openInputStream(uri);
        if (in == null) {
            throw new IOException("The picker returned a location that cannot be read");
        }
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buffer = new byte[8192];
            int read;
            int total = 0;
            while ((read = in.read(buffer)) != -1) {
                total += read;
                if (total > MAX_IMPORT_BYTES) {
                    throw new IOException("That file is too large to be a backup");
                }
                out.write(buffer, 0, read);
            }
            return new String(out.toByteArray(), StandardCharsets.UTF_8);
        } finally {
            try {
                in.close();
            } catch (IOException ignored) {}
        }
    }
}
